name: ci
on: pull_request

jobs:
  static-checks:
    name: Static checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7

        with:
          python-version: "3.14.7"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pre-commit
        run: pre-commit run --all-files
